version: '3.6'

services:
  api:
    build: ./api/
    container_name: api
    volumes:
      - ./api/:/app
    working_dir: /app
    command: puma
    expose:
      - 3000
    ports:
      - 5000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    container_name: db
    image: postgres:10.3-alpine
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    working_dir: /usr/src/app
    command: npm start
    ports:
      - 4000:3000
    links:
      - api
    environment:
      NODE_ENV: development
